fix
pastuhov/yii2-logstock pull request #18
Opened 2019-01-09 13:13 UTC by michkarevev

2019-01-09 14:46 UTC, pastuhov requested changes
хорошо бы название ПРа отражало суть

2019-01-09 14:46 UTC, pastuhov commented on Module.php
> +            $manifest = unserialize($content);
покажи в тесте суть своего изменения плз

2019-01-09 14:46 UTC, pastuhov commented on UnitHelper.php
> +        $app->getLog()->getLogger()->flush();
для чего это изменение?

2019-01-10 10:12 UTC, michkarevev commented on UnitHelper.php
> +        $app->getLog()->getLogger()->flush();
Это изменение нужно, что бы flush отработал до включения сбора логстоков, иначе при вызове flush туда попадут все изменения, раньше оно работало правильно из-за flushInterval=1

2019-01-10 10:17 UTC, michkarevev commented
Так же почему-то не были добавлены два логстока, добавил их

2019-01-10 10:23 UTC, pastuhov approved these changes

2019-01-10 10:24 UTC, merged